# Generated by Django 3.0.5 on 2020-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(verbose_name='call_date')),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
    ]
