# Generated by Django 3.0.5 on 2020-04-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_weatherpresentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherPresentation',
        ),
    ]
