# Generated by Django 3.0.5 on 2020-05-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ChoiceSaved',
            name="session",
            field= models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_saved', to='service_development.CallSession', null=True)
        ),
    ]
