# Generated by Django 3.0.5 on 2020-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0003_delete_weatherpresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='is_weather_element',
            field=models.BooleanField(default=False, verbose_name='This element contains weather forecasts'),
        ),
    ]
