# Generated by Django 3.0.5 on 2020-04-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_voiceservicesubelement_is_weather_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_wind_normal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_normal_wind', to='service_development.VoiceLabel', verbose_name='Voice label normal wind'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_wind_strong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_strong_wind', to='service_development.VoiceLabel', verbose_name='Voice label strong wind'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='wind_threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind Threshold'),
        ),
    ]
