# Generated by Django 3.0.5 on 2020-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0005_auto_20200426_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceservicesubelement',
            name='wind_threshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind Threshold (km/h)'),
        ),
    ]
