# Generated by Django 3.0.5 on 2020-04-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0006_auto_20200430_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_friday', to='service_development.VoiceLabel', verbose_name='Voice label friday'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_monday', to='service_development.VoiceLabel', verbose_name='Voice label monday'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_0', to='service_development.VoiceLabel', verbose_name='Voice label rain 0'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_10', to='service_development.VoiceLabel', verbose_name='Voice label rain 10'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_15', to='service_development.VoiceLabel', verbose_name='Voice label rain 15'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_20', to='service_development.VoiceLabel', verbose_name='Voice label rain 20'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_25', to='service_development.VoiceLabel', verbose_name='Voice label rain 25'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_30', to='service_development.VoiceLabel', verbose_name='Voice label rain 30'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_35',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_35', to='service_development.VoiceLabel', verbose_name='Voice label rain 35'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_5', to='service_development.VoiceLabel', verbose_name='Voice label rain 5'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_saturday', to='service_development.VoiceLabel', verbose_name='Voice label saturday'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_sunday', to='service_development.VoiceLabel', verbose_name='Voice label sunday'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_thursday', to='service_development.VoiceLabel', verbose_name='Voice label thursday'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_today',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_today', to='service_development.VoiceLabel', verbose_name='Voice label today'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_tomorrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_tomorrow', to='service_development.VoiceLabel', verbose_name='Voice label tomorrow'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_tuesday', to='service_development.VoiceLabel', verbose_name='Voice label tuesday'),
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_wednesday', to='service_development.VoiceLabel', verbose_name='Voice label wednesday'),
        ),
    ]
