# Generated by Django 3.0.5 on 2020-05-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0007_auto_20200430_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_0_to_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_0_to_5', to='service_development.VoiceLabel', verbose_name='Voice label rain 0 to 5'),
        ),
    ]
