# Generated by Django 3.0.5 on 2020-05-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0008_voiceservicesubelement_voice_label_rain_0_to_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_friday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_monday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_0',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_0_to_5',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_10',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_15',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_20',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_25',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_30',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_35',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_rain_5',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_saturday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_sunday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_thursday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_today',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_tomorrow',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_tuesday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_wednesday',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_wind_normal',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='voice_label_wind_strong',
        ),
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='wind_threshold',
        ),
        migrations.CreateModel(
            name='WeatherManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Date last modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('wind_threshold', models.IntegerField(blank=True, null=True, verbose_name='Wind Threshold (km/h)')),
                ('service', models.ForeignKey(help_text='The service to which this element belongs', on_delete=django.db.models.deletion.CASCADE, to='service_development.VoiceService')),
                ('voice_label_rain_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_0', to='service_development.VoiceLabel', verbose_name='Voice label rain 0')),
                ('voice_label_rain_0_to_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_0_to_5', to='service_development.VoiceLabel', verbose_name='Voice label rain 0 to 5')),
                ('voice_label_rain_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_10', to='service_development.VoiceLabel', verbose_name='Voice label rain 10')),
                ('voice_label_rain_15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_15', to='service_development.VoiceLabel', verbose_name='Voice label rain 15')),
                ('voice_label_rain_20', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_20', to='service_development.VoiceLabel', verbose_name='Voice label rain 20')),
                ('voice_label_rain_25', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_25', to='service_development.VoiceLabel', verbose_name='Voice label rain 25')),
                ('voice_label_rain_30', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_30', to='service_development.VoiceLabel', verbose_name='Voice label rain 30')),
                ('voice_label_rain_35', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_35', to='service_development.VoiceLabel', verbose_name='Voice label rain 35')),
                ('voice_label_rain_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_rain_5', to='service_development.VoiceLabel', verbose_name='Voice label rain 5')),
                ('voice_label_wind_normal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_normal_wind', to='service_development.VoiceLabel', verbose_name='Voice label normal wind')),
                ('voice_label_wind_strong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_label_strong_wind', to='service_development.VoiceLabel', verbose_name='Voice label strong wind')),
            ],
            options={
                'verbose_name': 'Voice Service Weather Manager',
            },
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='weather_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.WeatherManager', verbose_name='Weather Manager'),
        ),
    ]
