# Generated by Django 3.0.5 on 2020-05-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0009_auto_20200510_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='weather_manager',
        ),
        migrations.AddField(
            model_name='voiceservice',
            name='weather_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.WeatherManager', verbose_name='Weather Manager'),
        ),
    ]
