# Generated by Django 3.0.5 on 2020-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0010_auto_20200510_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceservicesubelement',
            name='is_weather_element',
        ),
        migrations.AddField(
            model_name='voiceservice',
            name='is_weather_service',
            field=models.BooleanField(default=False, verbose_name='This element contains weather forecasts'),
        ),
    ]
