# Generated by Django 3.0.5 on 2020-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0011_auto_20200510_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='day_index',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
        migrations.AlterField(
            model_name='voiceservice',
            name='is_weather_service',
            field=models.BooleanField(default=False, verbose_name='Weather Service'),
        ),
    ]
