# Generated by Django 3.0.5 on 2020-05-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0012_auto_20200510_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceservice',
            name='is_weather_service',
        ),
        migrations.AddField(
            model_name='voiceservicesubelement',
            name='is_forecast',
            field=models.BooleanField(default=False, verbose_name='Is forecast message'),
        ),
    ]
